######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 20 20:04:24 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG +=console
# Input
SOURCES += main.cpp
