######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 25 08:00:36 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += QtTest.cpp
