######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 16 22:49:00 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += rectangledialog.h
SOURCES += main.cpp rectangledialog.cpp
