######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 8 22:03:45 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += rectangledialog.ui
SOURCES += main.cpp
