######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 21 22:24:01 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG +=console
# Input
SOURCES += test.cpp

HEADERS += \
    MinHeap.h \
    pqueue.h
