######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 8 22:25:26 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += scalabledialog.ui
SOURCES += main.cpp
